id: P8BE37C65
initial_creation_type: ocr
source_metadata:
  volumes:
    825e2319780543a8acdf2ecef745b369:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཡི་གེ་བརྒྱ་པ་ཞེས་བྱ་བའི་འགྲེལ་པ།
      total_pages: 1605
      volume_number: 57
